source 'https://rubygems.org'

gem 'sinatra', require: false
gem 'sinatra-flash'
gem 'haml'
gem 'coffee-script'
gem 'sass'
gem 'json'

group :development do
  gem 'sinatra-contrib', require: 'sinatra/reloader'
  gem 'pry'
end

group :test do
  gem 'rspec', '3.0.0'
  gem 'cucumber', '1.3.15'
  gem 'capybara'
  gem 'selenium-webdriver'
end

