source 'https://rubygems.org'

gem 'sinatra', :require => false
gem 'sinatra-flash'
gem 'haml'
gem 'coffee-script'
gem 'sass'

group :development do
  gem 'pry'
  gem 'sinatra-reloader'
end

group :test do
  gem 'rspec', '3.0.0'
  gem 'cucumber', '1.3.15'
  gem 'capybara'
end

